# ============================================================================
# generate_replicates — 从单次测量值生成伪重复（噪声注入）
# 版本: 0.1 (dev)
# 依赖: stats（base R 自带）
# ============================================================================
#
# !! 安全警告 / SAFETY NOTICE !!
# 本函数生成的是「人为合成」的伪重复值，不是真实的独立生物学/技术重复。
# 仅用于探索性可视化、占位图、demo。
# 严禁直接用这些伪重复跑假设检验（t 检验/ANOVA 等）或将结果写入正式论文的
# 统计结论——那是编造数据。每次调用都会打印 warning，并在返回值上打标记
# (attr(x, "synthetic") == TRUE) 供下游代码/审查识别。
#
# 用法: source("R/r_functions/lib/data_simulation/generate_replicates.R")

# ============================================================================
# 0. 内部工具：安全阀（每次调用都打标记 + 警告）
# ============================================================================

.grf_tag_synthetic <- function(x, type) {
  warning(
    "generate_replicates(): 返回值是由单次观测值人为生成的伪重复（noise-injected），",
    "不是真实的独立生物学/技术重复，仅供探索性可视化/占位使用。",
    "不得直接用于假设检验（t 检验等）或作为论文正式统计结论的依据。 [type = ", type, "]",
    call. = FALSE
  )
  attr(x, "synthetic") <- TRUE
  attr(x, "synthetic_type") <- type
  attr(x, "synthetic_warning") <- paste0(
    "generated by generate_replicates() [type = ", type, "] - ",
    "not real replicates, do not use for hypothesis testing"
  )
  x
}

# ============================================================================
# 1. 各类型噪声策略（内部函数，均接受单个标量 value，返回长度 n 的 numeric）
# ============================================================================

.grf_continuous <- function(value, n, cv) {
  if (is.na(value)) return(rep(NA_real_, n))
  if (value == 0) {
    warning("continuous: 值为 0，SD 也为 0，返回 n 个 0", call. = FALSE)
    return(rep(0, n))
  }
  if (value < 0) {
    warning("continuous: 传入负值，SD 用 |value| 计算", call. = FALSE)
  }
  sd <- abs(value) * cv
  stats::rnorm(n, mean = value, sd = sd)
}

.grf_proportion <- function(value, n, cv, scale = "auto") {
  if (is.na(value)) return(rep(NA_real_, n))

  is_pct_input <- switch(scale,
    "0-1"   = FALSE,
    "0-100" = TRUE,
    "auto"  = value > 1
  )
  if (scale == "auto" && value > 1) {
    warning(
      "proportion: 值 > 1，自动按 0~100 格式处理（除以 100）。",
      "注意：0~1 和 0~100 两种格式在数值 <= 1 时无法从数值本身区分",
      "（例如 0.5 既可能是比例 50%，也可能是百分比 0.5%）。",
      "如果你的数据本身可能是很小的百分比（如抑制率 0.5%），",
      "请显式传入 scale = \"0-100\" 避免误判。",
      call. = FALSE
    )
  }

  value_01 <- if (is_pct_input) value / 100 else value
  if (value_01 <= 0 || value_01 >= 1) {
    stop(
      "proportion: 值为 0 或 1（100%）时 logit 无法计算（结果为 ±Inf）。value = ",
      value, call. = FALSE
    )
  }

  logit_val <- log(value_01 / (1 - value_01))
  logit_sd  <- cv * abs(logit_val) + 0.05
  logit_rep <- stats::rnorm(n, mean = logit_val, sd = logit_sd)
  result_01 <- stats::plogis(logit_rep)

  if (is_pct_input) result_01 * 100 else result_01
}

.grf_abundance <- function(value, n, cv, clip = TRUE) {
  if (is.na(value)) return(rep(NA_real_, n))
  if (value < 0) {
    stop("abundance: 值必须 >= 0，传入了 ", value, call. = FALSE)
  }
  if (value == 0) {
    warning("abundance: 值为 0，返回 n 个 0", call. = FALSE)
    return(rep(0, n))
  }

  log_val <- log1p(value)
  log_sd  <- cv * abs(log_val) + 0.01
  log_rep <- stats::rnorm(n, mean = log_val, sd = log_sd)
  result  <- expm1(log_rep)

  if (clip) {
    result <- pmin(pmax(result, 0), 1)
  } else if (any(result < 0 | result > 1)) {
    warning("abundance: 生成值超出 [0,1] 合法范围（clip=FALSE，未裁剪）", call. = FALSE)
  }
  result
}

.grf_count <- function(value, n, dispersion) {
  if (is.na(value)) return(rep(NA_real_, n))
  if (value < 0) {
    stop("count: 值必须 >= 0，传入了 ", value, call. = FALSE)
  }
  if (value == 0) {
    return(rep(0, n))
  }
  # 注意：rnbinom() 的 mu 参数不要求整数，这里不强制 round() 原始值，
  # 避免丢失精度（这一点与交接文档的原始设计不同，见 notes.md）。
  as.double(stats::rnbinom(n, mu = value, size = dispersion))
}

# ============================================================================
# 2. 主函数
# ============================================================================

#' 从单次测量值生成伪重复（噪声注入）
#'
#' @description
#' \strong{安全警告}：本函数生成的是人为合成的伪重复值，不是真实的独立重复。
#' 仅用于探索性可视化/占位，严禁直接用于假设检验或论文正式统计结论。
#' 每次调用都会打印 warning，返回值带 \code{attr(x, "synthetic") == TRUE} 标记。
#'
#' @param x 单个数值、数值向量，或 data.frame。
#' @param type 数据类型标签，必须显式指定（不做自动推断）：
#'   \code{"continuous"} / \code{"proportion"} / \code{"abundance"} / \code{"count"}。
#' @param n 每个数据点生成的重复数，默认 3。
#' @param cv 变异系数，用于 continuous/proportion/abundance，默认 0.05。
#' @param dispersion 负二项离散参数（size），用于 count，默认 3。
#' @param clip 有界数据（abundance）是否裁剪到合法范围 [0,1]，默认 TRUE。
#' @param seed 随机种子。传入时结果可重复，且不会污染全局随机状态
#'   （函数退出后自动恢复调用前的 \code{.Random.seed}）。
#' @param col data.frame 模式下的目标列名（字符串）。
#' @param scale proportion 类型专用：\code{"auto"}（默认，沿用 value > 1 时按
#'   百分比处理的启发式，遇到时会 warning 提示这个启发式的局限）/
#'   \code{"0-1"} / \code{"0-100"}——显式指定可避免 0~1 与 0~100 两种格式在
#'   数值 <= 1 时无法区分的问题。
#'
#' @return
#'   - 单值输入 → 长度为 n 的数值向量
#'   - 向量输入 → 矩阵（行 = 原始数据点，列 = 重复），\code{n = 1} 时也返回矩阵（1 列），保持类型稳定
#'   - data.frame 输入 → 原数据框新增 \code{col_rep1...col_repN} 列
#'
#'   返回值均带 \code{synthetic} / \code{synthetic_type} / \code{synthetic_warning} attribute。
#'
#' @examples
#' generate_replicates(0.75, type = "proportion", n = 3, seed = 1)
#' generate_replicates(c(0.12, 0.08, 0.15), type = "abundance", n = 3, seed = 1)
generate_replicates <- function(
    x,
    type,
    n          = 3,
    cv         = 0.05,
    dispersion = 3,
    clip       = TRUE,
    seed       = NULL,
    col        = NULL,
    scale      = c("auto", "0-1", "0-100")
) {
  type  <- match.arg(type, c("continuous", "proportion", "abundance", "count"))
  scale <- match.arg(scale)

  if (!is.numeric(n) || length(n) != 1 || is.na(n) || n < 1 || n != round(n)) {
    stop("n 必须是 >= 1 的整数")
  }
  n <- as.integer(n)
  if (!is.numeric(cv) || cv <= 0) stop("cv 必须是正数")
  if (!is.numeric(dispersion) || dispersion <= 0) stop("dispersion 必须是正数")

  # ---- RNG 隔离：不污染调用者的全局随机状态 ----
  if (!is.null(seed)) {
    if (!exists(".Random.seed", envir = .GlobalEnv)) stats::runif(1)
    old_seed <- get(".Random.seed", envir = .GlobalEnv)
    on.exit(assign(".Random.seed", old_seed, envir = .GlobalEnv), add = TRUE)
    set.seed(seed)
  }

  generator <- switch(type,
    continuous = function(v) .grf_continuous(v, n, cv),
    proportion = function(v) .grf_proportion(v, n, cv, scale),
    abundance  = function(v) .grf_abundance(v, n, cv, clip),
    count      = function(v) .grf_count(v, n, dispersion)
  )

  # ---- data.frame 模式 ----
  if (is.data.frame(x)) {
    if (is.null(col)) stop("x 是 data.frame 时必须指定 col 参数")
    if (!col %in% names(x)) stop("列 '", col, "' 不存在于 data.frame 中")
    values <- x[[col]]
    if (!is.numeric(values)) stop("列 '", col, "' 必须是数值列")

    reps <- do.call(rbind, lapply(values, generator))
    colnames(reps) <- paste0(col, "_rep", seq_len(n))
    out <- cbind(x, as.data.frame(reps))
    return(.grf_tag_synthetic(out, type))
  }

  # ---- 数值输入 ----
  if (!is.numeric(x)) stop("x 必须是数值、数值向量或 data.frame")

  if (length(x) == 1) {
    result <- generator(x)
    return(.grf_tag_synthetic(result, type))
  }

  # 向量输入 -> 矩阵（行 = 数据点，列 = 重复），n=1 时也保持矩阵，类型稳定
  # 用 lapply + rbind 而不是 vapply(x, generator, numeric(n))：
  # vapply 在 n == 1 时会把结果 simplify 成向量，丢失矩阵结构。
  reps <- do.call(rbind, lapply(x, generator))
  colnames(reps) <- paste0("rep", seq_len(n))
  rownames(reps) <- NULL
  .grf_tag_synthetic(reps, type)
}
